  manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # - name: kumamuk-git
    #   url-base: https://github.com/kumamuk-git
    - name: sayu-hub
      url-base: https://github.com/sayu-hub
    - name: caksoylar  # <-- new entry
      url-base: https://github.com/caksoylar  
    - name: kot149
      url-base: https://github.com/kot149
    # - name: carrefinho                            # <--- add this
    #   url-base: https://github.com/carrefinho     # <--- and this
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2.1
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: main
    # - name: zmk-pmw3610-driver
    #   remote: sayu-hub
    #   revision: main
    - name: zmk-rgbled-widget  # <-- new entry
      remote: caksoylar
      revision: main
    - name: zmk-layout-shift
      remote: kot149
      revision: v1
    # - name: prospector-zmk-module
    #   remote: carrefinho
    #   revision: main
    #   kconfig: boards/shields/prospector_adapter/Kconfig

  self:
    path: config
